version: '3'

services:
  rosserial:
    container_name: rosserial
    labels:
      project: openmower
      app: rosserial
    image: ghcr.io/jeremysalwen/rosserial-services-docker:main
    network_mode: host
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      ROS_MASTER_URI: ${ROS_MASTER_URI:-http://127.0.0.1:11311}
      ROS_IP: ${ROS_IP:-127.0.0.1}
      PORT: ${PORT:-/dev/mowgli}
      BAUD: ${BAUD:-115200}
    volumes:
      - /dev:/dev
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
